### ISSUE TITLE
runtime error: env is not defined [29:13] in ./src/main.ink

### ISSUE THREAD

**Issue by psquared2** [thesephist/inc#1]
I [installed Ink](https://dotink.co/docs/overview/#setup-and-installation) on CentOS 7 and downloaded the latest inc repository ([ffb9285](https://github.com/thesephist/inc/commit/ffb92852d5ad9186f7c352754487d22ecac8fb28)) - but I'm running into an error, as stated in the title above.

**Comment by thesephist** [comment]
Ah, looks like the latest release of Ink on the GitHub repo doesn't include the [`env()` built-in function](https://dotink.co/docs/runtime/#env) and a few other more recent changes. Let me update that release real quick—

**Comment by psquared2** [comment]
Thank you! Looking forward to using Inc.

**Comment by thesephist** [comment]
I got a little bit lazy, so instead of making a new release I just updated the 1.9 release 😅 

If you install Ink again from the same release — https://github.com/thesephist/ink/releases/tag/v0.1.9 — you should have the couple of commits that were missing in the previous build, and inc should run properly. Thanks for catching the mistake!
